import { and, desc, eq, gt, sql } from "drizzle-orm";
import { getDb } from "@/lib/db";
import {
  airportReviewImages,
  airportReviews,
  type AirportReviewRow,
} from "@/lib/db/schema";
import {
  fetchReviewImageRows,
  rowToReviewImage,
  type ProcessedReviewImage,
} from "@/lib/review-images";
import type {
  AirportUserReview,
  ReviewFormValues,
  ReviewImage,
} from "@/lib/review-schema";

const MAX_REVIEWS_LISTED = 50;
const MAX_REVIEWS_PER_IP_PER_HOUR = 5;

function toAirportUserReview(
  row: AirportReviewRow,
  images: ReviewImage[] = [],
): AirportUserReview {
  return {
    id: row.id,
    author: row.author,
    tripType: row.tripType,
    rating: row.rating,
    title: row.title,
    body: row.body,
    createdAt: row.createdAt.toISOString(),
    images,
  };
}

/**
 * Second query rather than a join: the row count is bounded by
 * MAX_REVIEWS_LISTED, and most reviews have no photos at all.
 */
async function attachImages(rows: AirportReviewRow[]): Promise<AirportUserReview[]> {
  if (rows.length === 0) {
    return [];
  }

  const imageRows = await fetchReviewImageRows(rows.map((row) => row.id));
  const byReview = new Map<string, ReviewImage[]>();

  for (const imageRow of imageRows) {
    const images = byReview.get(imageRow.reviewId);

    if (images) {
      images.push(rowToReviewImage(imageRow));
    } else {
      byReview.set(imageRow.reviewId, [rowToReviewImage(imageRow)]);
    }
  }

  return rows.map((row) => toAirportUserReview(row, byReview.get(row.id) ?? []));
}

export async function getReviewsByIata(iata: string): Promise<AirportUserReview[]> {
  const rows = await getDb()
    .select()
    .from(airportReviews)
    .where(
      and(
        eq(airportReviews.iata, iata),
        eq(airportReviews.status, "published"),
        eq(airportReviews.source, "community"),
      ),
    )
    .orderBy(desc(airportReviews.createdAt))
    .limit(MAX_REVIEWS_LISTED);

  return attachImages(rows);
}

/** Curated reviews seeded from our own scoring/editorial process, shown as a separate lane. */
export async function getEditorialReviewsByIata(iata: string): Promise<AirportUserReview[]> {
  const rows = await getDb()
    .select()
    .from(airportReviews)
    .where(
      and(
        eq(airportReviews.iata, iata),
        eq(airportReviews.status, "published"),
        eq(airportReviews.source, "editorial"),
      ),
    )
    .orderBy(desc(airportReviews.createdAt))
    .limit(MAX_REVIEWS_LISTED);

  return attachImages(rows);
}

/**
 * Checked by the route before it processes any uploads — a rate-limited caller
 * must not get as far as writing blobs we'd then have to clean up.
 */
export async function isReviewRateLimited(ipHash: string | null): Promise<boolean> {
  if (!ipHash) {
    return false;
  }

  const [recent] = await getDb()
    .select({ count: sql<number>`count(*)::int` })
    .from(airportReviews)
    .where(
      and(
        eq(airportReviews.ipHash, ipHash),
        gt(airportReviews.createdAt, sql`now() - interval '1 hour'`),
      ),
    );

  return (recent?.count ?? 0) >= MAX_REVIEWS_PER_IP_PER_HOUR;
}

/**
 * The review id is generated by the caller so uploaded blobs can be keyed by it
 * before the row exists. Photos are inserted in the same transaction as the
 * review and returned with it, so the form can render the new card — complete
 * with thumbnails — without a refetch.
 */
export async function createReview({
  id,
  iata,
  values,
  ipHash,
  userId,
  images = [],
}: {
  id: string;
  iata: string;
  values: ReviewFormValues;
  ipHash: string | null;
  userId?: string;
  images?: ProcessedReviewImage[];
}): Promise<AirportUserReview> {
  return getDb().transaction(async (tx) => {
    const [row] = await tx
      .insert(airportReviews)
      .values({
        id,
        iata,
        author: values.author,
        tripType: values.tripType,
        rating: values.rating,
        title: values.title,
        body: values.body,
        ipHash,
        userId: userId ?? null,
      })
      .returning();

    if (images.length === 0) {
      return toAirportUserReview(row);
    }

    const imageRows = await tx
      .insert(airportReviewImages)
      .values(
        images.map((image, index) => ({
          reviewId: row.id,
          url: image.url,
          alt: image.alt,
          caption: image.caption,
          width: image.width,
          height: image.height,
          sortOrder: index,
          // Stored for inspection only — `rowToReviewImage` deliberately leaves
          // these out, so they never reach a client.
          takenAt: image.exif.takenAt,
          gpsLatitude: image.exif.latitude,
          gpsLongitude: image.exif.longitude,
          gpsDistanceKm: image.gpsDistanceKm,
        })),
      )
      .returning();

    return toAirportUserReview(row, imageRows.map(rowToReviewImage));
  });
}
